language: python

python:
  - "2.7"

# blocklist
branches:
  except:
  - master

# safelist
branches:
  only:
  - dev

env:
  # Github deployment key
  - secure: "ysREnBli0KDfHDlG3IFLtBtSHflSu3fdAaRMdar90Mq9EFrcJBMJllZ9OQPP3ot2fYfVEddkWJHS2LXBy5KY7teiSXoWkgoBPFXPhVhArVzA0wh/vhSuPyh2SgHsxA6uDfg/p8MAC3tQycEvBQiX3FwZTHX5KHk2wY9NIhlnBjdZ02ZJKHz400YNpKoBs5jfjWHrxPlyIaTrb0cN57rsm+qCYJ4MrSH8AxMu6KOEeiZ50OzbyBFGRcVv3w5F+sNPFUaHIhaRpGd7+epzK+BdYE6PH3K37sFEG2Keyz2uWfpaRo5ePQnd3T6L9kdO3R793tgtj5B8b79w1kHsRUfkxedDD4xBBYZfFr0SbgF3j4/4rqy+EphzsRamDbUe9X6jn5f6bMwwsK0cw4nHTapohyWqWBIGffgswVoW3G2BM/oKK6YlIbC7Srr0GHTt73cw+vWaiaujjLiezcBF5fwOEdf/1I2VDwYcqs7SQGNb54Ibj/kDgy/uIag/V8PEhIi9VE+H+swHPvyP8T7nz8TGbB7pqThaf5b8MsZOcAcmjM2c5ykgUbgKQV90dEMqc43Q+pQVmqNxK58nlL2vUAZbaN/rT1JYElCLebdfxY9AIgGyhM/c9M2MVMJCvuEtYqXve5gcwNmQLO98cS8W8Umj8v5nwZdvMThKJSy5xCAj6LM="

install:
  - pip install pystache requests pygithub3

sudo: false

cache: pip

script:
 - python shellcommit.py

after_success: 
  - build.sh
